version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony_web
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV=dev

  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./backend:/var/www/backend
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/snippets:/etc/nginx/snippets
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  db_data:
